language: python
python:
- '3.4'
- '3.3'
- '2.7'
install: pip install -r requirements-dev.txt
script: python setup.py test
deploy:
  provider: pypi
  user: sdementen
  password:
    secure: kIW3wjCwmXVO5XyCU9SjT4NZxAcq/9XBjHKN5HuD8ACZzlaqxU3UI8YKTE3O8XFNaT56/6bySLDrR83O4+s7bcIW/tWacky5PqKSkTuYhyQfnggHn4EQC5iDBSYYONPIBwIMb28pCLps3HMAT2F868iGHpFge7hr+YQBwZ5O1Io=
  on:
    tags: true
    repo: sdementen/piecash
